---
- name: Pull docker image of model
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull rk007again/medi1:latest
